"""
Optimized Strategy Configuration - 优化后的策略配置
Generated by Autoresearch at 2026-03-23T21:36:03.402384
"""
from dataclasses import dataclass
from typing import Optional

@dataclass
class StrategyConfig:
    """优化后的策略配置"""
    
    # === 基础参数 ===
    initial_capital: float = 10000.0
    max_position_per_stock: float = 0.25
    commission_rate: float = 0.0003
    stamp_duty_rate: float = 0.001
    
    # === 持仓周期 ===
    min_hold_days: int = 1
    max_hold_days_short: int = 3
    max_hold_days_medium: int = 10
    
    # === 止损止盈 ===
    hard_stop_loss: float = -0.05
    trailing_stop: bool = True
    trailing_stop_pct: float = 0.1
    profit_target: Optional[float] = 0.20
    
    # === 趋势因子 ===
    use_ma_trend: bool = True
    ma_short: int = 20
    ma_medium: int = 50
    require_ma_bullish: bool = True
    
    # === 动量因子 ===
    use_momentum: bool = True
    momentum_lookback: int = 20
    momentum_min: float = 0.1
    momentum_max: float = 0.3
    
    # === 量能因子 ===
    use_volume: bool = True
    volume_ma_period: int = 5
    volume_surge_ratio: float = 1.5
    
    # === 波动因子 ===
    use_volatility: bool = True
    atr_period: int = 14
    max_atr_pct: float = 0.05
    
    # === 风控参数 ===
    max_positions: int = 5
    max_daily_trades: int = 3
    max_drawdown_limit: float = -0.15
    
    # === 信号强度 ===
    min_signal_score: float = 0.6

CURRENT_CONFIG = StrategyConfig()
